version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - 8071:80
      - 8072:443

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/
# in case of error "[pool www] user has not been defined" uncomment following lines
#      - ./.docker/php/htdocs:/var/www/htdocs
#      - ./.docker/php/docker.conf:/etc/php/8.3/fpm/pool.d/docker.conf
#      - ./.docker/php/www.conf:/etc/php/8.3/fpm/pool.d/www.conf
#      - ./.docker/php/zz-docker.conf:/etc/php/8.3/fpm/pool.d/zz-docker.conf
    environment:
      NETTE_DEBUG: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 0
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_INTL: 1
      STARTUP_COMMAND_1: composer install
      STARTUP_COMMAND_2: composer install
      STARTUP_COMMAND_3: NETTE_DEBUG=1 php -v
